language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t praveenkumar081097/testimage_reactapp -f Dockerfile.dev .
scripts:
  - docker run -e CI=true praveenkumar081097/docker-react npm run test
